buildscript {
  repositories {
    mavenCentral()
    gradlePluginPortal()
    mavenLocal()
    google()
    maven { url = 'https://central.sonatype.com/repository/maven-snapshots/' }
  }
  dependencies {
  }
}

allprojects {
  apply plugin: 'eclipse'
  apply plugin: 'idea'

  tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
  }

  idea {
    module {
      outputDir = file('build/classes/java/main')
      testOutputDir = file('build/classes/java/test')
    }
  }
}

configure(subprojects) {
  apply plugin: 'java-library'
  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(21)
    }
  }

  tasks.register('generateAssetList') {
    inputs.dir("${project.rootDir}/assets/")
    File assetsFolder = new File("${project.rootDir}/assets/")
    File assetsFile = new File(assetsFolder, "assets.txt")
    assetsFile.delete()
    fileTree(assetsFolder).collect { assetsFolder.relativePath(it) }.sort().each {
      assetsFile.append(it + "\n")
    }
  }
  processResources.dependsOn 'generateAssetList'

  compileJava {
    options.incremental = true
  }
}

apply from: 'scripts/dev-tools.gradle'

version = '1.0.0'

ext {
    gdxVersion = '1.12.1'
    ashleyVersion = '1.7.3'
    aiVersion = '1.8.2'
    kryoVersion = '5.5.0'
    luajVersion = '3.0.1'
    junitVersion = '5.10.1'
    jmhVersion = '1.37'
    jacksonVersion = '2.15.4'
    graalHelperVersion = '0.4.0'
    enableGraalNative = 'false'
    projectVersion = rootProject.version
}

subprojects {
  version = rootProject.version
  ext.appName = 'staraxis'
  repositories {
    mavenCentral()
    mavenLocal()
    maven { url = 'https://central.sonatype.com/repository/maven-snapshots/' }
    maven { url = 'https://jitpack.io' }
  }
}

eclipse.project.name = 'staraxis-parent'
