[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  // 依赖 shared：协议/常量
  implementation project(':shared')
  // core 模块只保留纯逻辑、无平台依赖的三方库
  api "com.bladecoder.ink:blade-ink:$bladeInkVersion"
  api "com.github.tommyettinger:regexodus:$regExodusVersion"
  api "net.onedaybeard.artemis:artemis-odb:$artemisOdbVersion"
  api "org.apache.commons:commons-collections4:$commonsCollectionsVersion"
}
