[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  // core 模块现在只保留纯逻辑、无平台依赖的库
  api "com.bladecoder.ink:blade-ink:$bladeInkVersion"
  api "com.github.tommyettinger:regexodus:$regExodusVersion"
  api "net.onedaybeard.artemis:artemis-odb:$artemisOdbVersion"
  api "org.apache.commons:commons-collections4:$commonsCollectionsVersion"
}
