[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

eclipse.project.name = appName + '-server'

apply plugin: 'application'

application {
  mainClass = 'staraxis.server.ServerMain'
}

dependencies {
  api project(':core')
  implementation "io.netty:netty-all:4.1.97.Final"
  implementation "com.google.code.gson:gson:2.10.1"
  api project(':shared')
}
